spring.application.name=orderandinventory

spring.datasource.url=jdbc:postgresql://localhost:5432/b2border
spring.datasource.username=test
spring.datasource.password=OrderB2B
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true

spring.jpa.hibernate.ddl-auto=update